#control the physics
#/control/execute physics.mac
/physic/addPhysics HADRONTHERAPY_2
#/tracking/verbose 1
/run/numberOfThreads 32
/run/initialize
#/changeTarget/Material G4_BRAIN_ICRP
/changeTarget/Size 100 1000 1000 um

/gps/particle proton
/gps/position -0.5 0 0 cm
/gps/direction 1  0 0
/gps/ene/mono 4 MeV

#/random/setSeeds 1 1
#/run/setCut 1 um
/run/printProgress 200000000
/run/beamOn 2000000000
